/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Discount.h
 #	source generated by 4D Plugin Wizard
 #	Project : Discount
 #	author : miyako
 #	2019/12/16
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_DISCOUNT_H
#define PLUGIN_DISCOUNT_H

#include "4DPluginAPI.h"
#include "C_TEXT.h"
#include "C_LONGINT.h"

#pragma mark -

void Markdown(PA_PluginParameters params);

#include "mkdio.h"
#include "markdown.h"
#include "tags.h"
#include "toc.h"
#include "css.h"

#include <iostream>
#include <sstream>

#define MKD_GITHUB_FLAVOURED 1
#define MKD_WITH_HTML5_TAGS 2


#endif /* PLUGIN_DISCOUNT_H */
