/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Discount
 #	author : miyako
 #	2013/10/18
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"

// --- Discount
void Markdown(sLONG_PTR *pResult, PackagePtr pParams);

#include "mkdio.h"
#include "markdown.h"
#include "tags.h"
#include "toc.h"
#include "css.h"

#include <iostream>
#include <sstream>

#define MKD_GITHUB_FLAVOURED 1
#define MKD_WITH_HTML5_TAGS 2